version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: hesabyarehonar_co
    environment:
      POSTGRES_USER: hesabyarehonar
      POSTGRES_PASSWORD: Reza1359@@
      POSTGRES_DB: hesabyarehonar_db
    ports:
      - "5433:5432"   # پورت هاست 5433 تا با mahan_db تداخل نکنه
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
